import { Resource } from '@/components/resource/ResourceCard';

export const mockResources: Resource[] = [
  {
    id: "r1",
    title: "Panduan Lengkap Next.js App Router untuk Pemula",
    url: "https://nextjs.org/docs/app",
    description: "Dokumentasi resmi dan panduan komprehensif cara menggunakan fitur terbaru dari Next.js yaitu App Router. Termasuk cara fetch data, routing, dan optimasi.",
    resource_type: "Documentation",
    difficulty_level: "Beginner",
    category: "Frontend",
    tech_stack_tags: ["Next.js", "React", "TypeScript"],
    submitted_by: { username: "budi_dev" },
    score: 145,
    comment_count: 23,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "r2",
    title: "Supabase: Alternatif Firebase Open Source dengan PostgreSQL",
    url: "https://supabase.com",
    description: "Database backend as a service yang sangat powerful dengan dukungan PostgreSQL, real-time subscriptions, dan built-in authentication.",
    resource_type: "Tool",
    difficulty_level: "All",
    category: "Database",
    tech_stack_tags: ["Supabase", "PostgreSQL", "Backend"],
    submitted_by: { username: "siti_coder" },
    score: 98,
    comment_count: 15,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "r3",
    title: "Kumpulan Boilerplate Auth Next.js + Tailwind + Supabase",
    url: "https://github.com/vercel/nextjs-subscription-payments",
    description: "Repository starter kit yang siap pakai untuk membuat aplikasi SaaS dengan fitur subscription dari Stripe dan autentikasi Supabase.",
    resource_type: "Boilerplate",
    difficulty_level: "Intermediate",
    category: "Fullstack",
    tech_stack_tags: ["Next.js", "Tailwind", "Supabase", "Stripe"],
    submitted_by: { username: "joko_stack" },
    score: 210,
    comment_count: 42,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "r4",
    title: "Membuat Sistem Design yang Scalable dengan Tailwind v4",
    url: "https://tailwindcss.com/docs",
    description: "Artikel bagus tentang cara mendesain utility classes yang rapi dan maintainable di project berskala besar.",
    resource_type: "Article",
    difficulty_level: "Advanced",
    category: "UI/UX",
    tech_stack_tags: ["Tailwind", "CSS"],
    submitted_by: { username: "ui_ninja" },
    score: 67,
    comment_count: 8,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "r5",
    title: "Belajar TypeScript dari Nol sampai Mahir",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    description: "Tutorial lengkap memahami strict typing di JavaScript untuk menghindari runtime errors di production.",
    resource_type: "Tutorial",
    difficulty_level: "Beginner",
    category: "Frontend",
    tech_stack_tags: ["TypeScript", "JavaScript"],
    submitted_by: { username: "ts_master" },
    score: 180,
    comment_count: 31,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  }
];
